[package]
name = "useadb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adbridger = { path = "../adbridger" }

clap = "*"
dialoguer = "*"
crossterm = "*"
console = "*"